### ISSUE TITLE
WebElement.scrollIntoView()

### ISSUE THREAD

**Issue by clonejo** [CasparKielwein/cadmium#14]
Often it is required to scroll an element into view before interacting with it.

One way to do that in Selenium is
```(driver as JavascriptExecutor).executeScript("arguments[0].scrollIntoView(true);", element)```

But since Cadmium does not expose the raw Selenium element, this route is blocked.

Cadmium could either offer a method to do this, or could do it implicitly before any interaction. Devs coming from Selenium would probably prefer the former, since there is less hidden magic.

**Comment by CasparKielwein** [comment]
There is a feature branch implementing the later.
https://github.com/CasparKielwein/cadmium/tree/move_into_view

I am conflicted on which solution would be the best.
Maybe we can come up with a nice interface for general configuration of cadmium. In the best case with the possibility for scoping.

**Comment by zaron** [comment]
Depending on the use-case the test needs to scoll to something. Something like 
```
alwaysScrollIntoView {
    // perform actions
}
```
would be a nice to have. It should not be enabled by default in my opinion.

**Comment by CasparKielwein** [comment]
I think in a first version I'll just add a variable to WebElement, which controls the  behaviour.
It can then be used like this:
```{kotlin}
element(Id("bla")) {
    autoScroll = true
    click()
}
```
